#!/bin/bash
# TODO: add option to read colors from file
#       allow custom delimiters
#       change format based on file type

declare -A colors
colors[black]="1d2021"
colors[red]="cc241d"
colors[green]="98971a"
colors[yellow]="d79921"
colors[blue]="458588"
colors[magenta]="b16286"
colors[cyan]="689d6a"
colors[white]="a89984"
colors[bright-black]="928374"
colors[brignt-red]="fb4934"
colors[bright-green]="b8bb26"
colors[bright-yellow]="fabd2f"
colors[bright-blue]="83a598"
colors[bright-magenta]="d3869b"
colors[bright-cyan]="8ec07c"
colors[bright-white]="ebdbb2"

torgb () {
	while read -r line; do
		for c in ${!colors[@]}; do
			line=${line//:$c:/${colors[$c]}}
		done
		echo $line
	done
}

torgb "$@"
